server:
  port: 8085
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_sms?useUnicode=true&characterEncoding=utf-8
  redis:
    host: 106.12.24.60
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/sms/**/*.xml