server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: wms-route
          uri: lb://wms-service
          predicates:
              - Path= /wms/**
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path= /pms/**

#        - id: oms-route
#            uri: lb://oms-service
#            predicates:
#              - Path= /oms/**
#        - id: ums-route
#            uri: lb://ums-service
#            predicates:
#              - Path= /ums/**
#        - id: sms-route
#            uri: lb://sms-service
#            predicates:
#              - Path= /sms/**
    nacos:
      server-addr: 127.0.0.1:8848