server:
  port: 8081
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_pms?useUnicode=true&characterEncoding=utf-8
  redis:
    host: 106.12.24.60
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/pms/**/*.xml
logging:
  level:
    top.shiyana.gmall.pms.dao: DEBUG